# Create a MongoDB API database and collection
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZ_CLIENT_ID }}
        tenant-id: ${{ secrets.AZ_TENANT_ID }}
        subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
    
    - name: Create MongoDB
      id: create-mongodb
      run: |
        account=srahul3AksMdb
        cosmos_account_name=voting
        echo "Creating $account"
        az cosmosdb create \
          --name $account \
          --subscription ${{ secrets.AZ_SUBSCRIPTION_ID }} \
          --resource-group ${{ secrets.AZ_RESOURCE_GROUP }} \
          --kind MongoDB \
          --default-consistency-level Eventual \
          --locations regionName=${{ secrets.AZ_LOCATION }}
          
        az cosmosdb database create \
          --subscription ${{ secrets.AZ_SUBSCRIPTION_ID }} \
          --resource-group ${{ secrets.AZ_RESOURCE_GROUP }} \
          --name $cosmos_account_name \
          --db-name $cosmos_db_name \
          --throughput 400

     
    
